### ISSUE TITLE
Error with creating sync video

### ISSUE THREAD

**Issue by Michel-NL** [SenorPez/project-cars-replay-enhancer-ui#29]
I tried two races with different config files and images. All having the same error message :(
```
michel@SRV-VM-UBUNTU:~/AOR/LMP2/round1$ replayenhancer -s config.json
Detecting Race End: 100%|████████| 284128/284128 [01:33<00:00, 3041.81packets/s]
Analyzing Telemetry Data: 100%|████████████████████████████████████████████▉| 283421/284128 [01:23<00:00, 3381.04packets/s]
Detecting Video Start: 8748it [00:07, 1115.56it/s]
Detecting Video End: 154it [00:00, 891.28it/s]
Traceback (most recent call last):
  File "/usr/local/bin/replayenhancer", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/replayenhancer/replayenhancer.py", line 448, in main
    sync=args.sync)
  File "/usr/local/lib/python3.5/dist-packages/replayenhancer/replayenhancer.py", line 155, in make_video
    result_data.get_data()
  File "/usr/local/lib/python3.5/dist-packages/replayenhancer/RaceData.py", line 235, in get_data
    self._add_sector_times(self._next_packet)
  File "/usr/local/lib/python3.5/dist-packages/replayenhancer/RaceData.py", line 280, in _add_sector_times
    self.drivers[driver_name].add_sector_time(sector_time)
KeyError: None
michel@SRV-VM-UBUNTU:~/AOR/LMP2/round1$
```
Just saw that I posted this in the UI project...wrong place?

**Comment by SenorPez** [comment]
Can you send me the telemetry for this race? It looks to be a problem with driver detection; thought I'd wrapped up all those issues!

**Comment by Michel-NL** [comment]
I have two telemetry sets for you

https://1drv.ms/u/s!AkpjgvuA0hKBmMoyxkYJeI3EePPKew
https://1drv.ms/u/s!AkpjgvuA0hKBmMozB93Mc5aKpDKPdw

**Comment by SenorPez** [comment]
I'm still working on this. I'm getting closer to having a solution, but you've stumped me so far!

Thanks for continuing to (try to) use this; I apologize that it's not working!

**Comment by SenorPez** [comment]
Release Candidate published. Follow the pip command here to install it (pip, by default, will ignore RCs):
https://github.com/SenorPez/project-cars-replay-enhancer/releases/tag/release-0.6rc1

I still need to make some fixes to the UI project for these changes, too, so this isn't ready for primetime just yet.

**Comment by SenorPez** [comment]
Oh, one last thing. Check your telemetry directories. If there's a `descriptor.json` file there, delete it. The change involved changes to how that file (which caches data about which packets are the actual race) is generated.

**Comment by SenorPez** [comment]
Also, you probably want to rebuild your JSON from scratch. The Java app does driver detection, so it might not have got all the drivers before, due to the error. I'm still running stability tests today, but it'll take a while because I can't devote 100% to it today. (Ugh, real life is a pain some days.)

**Comment by SenorPez** [comment]
New UI release candidate published. This should squash the bug. (I hope!)
https://github.com/SenorPez/project-cars-replay-enhancer-ui/releases/tag/release-0.2.2rc1
